### ISSUE TITLE
Authorization for translation

### ISSUE THREAD

**Issue by kassane** [NanXiao/boost-asio-network-programming-little-book#1]
Hi how are you?

Previously, I translated your book related to Asio (which by the way is excellent), because it is very scarce to find this type of material in my language. However, I realized that your book did not have any copyright license. If I happen to be inconvenient or want to license the project, I will do it without any problem.

So I just quote in the readme how to thank your username with the link of the original book.
https://github.com/kassane/ebook-net-prog

**Comment by NanXiao** [comment]
@kassane Thanks for enjoy my writing! I will license them as BSD license. So you can use these materials at your will, thanks!
